# Generated by Django 4.0.4 on 2023-03-01 23:41

import django.contrib.auth.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Nombre')),
                ('celular', models.CharField(max_length=255, verbose_name='Celular')),
                ('correo', models.EmailField(max_length=255, verbose_name='Correo')),
                ('calle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('colonia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Colonia')),
                ('municipio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mnicipio')),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código postal')),
                ('estado', models.CharField(blank=True, choices=[('Sin Estado', 'Sin Estado'), ('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Ciudad de México', 'Ciudad de México'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=35, null=True, verbose_name='Estado')),
                ('estatus_asesor', models.IntegerField(choices=[(1, 'Activo'), (3, 'Baja')], default=1, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Asesor',
                'verbose_name_plural': 'Asesores',
                'db_table': 'Asesor',
                'ordering': ['apellidos', 'nombre'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Bien',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calle', models.CharField(max_length=255, verbose_name='Calle')),
                ('numero', models.CharField(max_length=20, verbose_name='Número')),
                ('colonia', models.CharField(max_length=255, verbose_name='Colonia')),
                ('municipio', models.CharField(max_length=255, verbose_name='Municipio')),
                ('codigo_postal', models.CharField(max_length=5, verbose_name='Código postal')),
                ('estado', models.CharField(choices=[('Sin Estado', 'Sin Estado'), ('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Ciudad de México', 'Ciudad de México'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=35, verbose_name='Estado')),
                ('longitud', models.CharField(blank=True, max_length=15, null=True, verbose_name='Longitud')),
                ('latitud', models.CharField(blank=True, max_length=15, null=True, verbose_name='Latitud')),
                ('tipo', models.IntegerField(choices=[(0, 'Sin tipo'), (1, 'Casa'), (2, 'Departamento'), (3, 'Local comercial'), (4, 'Terreno')], default=0, verbose_name='Tipo bien')),
                ('compra', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0, verbose_name='Compra')),
                ('renta', models.IntegerField(choices=[(0, 'No'), (1, 'Si')], default=0, verbose_name='Renta')),
                ('estatus_bien', models.IntegerField(choices=[(1, 'Disponible'), (2, 'Apartado'), (3, 'Vendido'), (4, 'Reservado'), (9, 'Eliminado')], default=1, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Bien',
                'verbose_name_plural': 'Bienes',
                'db_table': 'Bien',
                'ordering': ['estado', 'municipio', 'colonia', 'calle', 'numero'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, verbose_name='Nombre')),
                ('apellidos', models.CharField(max_length=255, verbose_name='Nombre')),
                ('celular', models.CharField(max_length=255, verbose_name='Celular')),
                ('correo', models.EmailField(blank=True, max_length=255, null=True, verbose_name='Correo')),
                ('calle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Calle')),
                ('numero', models.CharField(blank=True, max_length=20, null=True, verbose_name='Número')),
                ('colonia', models.CharField(blank=True, max_length=255, null=True, verbose_name='Colonia')),
                ('municipio', models.CharField(blank=True, max_length=255, null=True, verbose_name='Municipio')),
                ('codigo_postal', models.CharField(blank=True, max_length=5, null=True, verbose_name='Código postal')),
                ('estado', models.CharField(blank=True, choices=[('Sin Estado', 'Sin Estado'), ('Aguascalientes', 'Aguascalientes'), ('Baja California', 'Baja California'), ('Baja California Sur', 'Baja California Sur'), ('Campeche', 'Campeche'), ('Coahuila', 'Coahuila'), ('Colima', 'Colima'), ('Chiapas', 'Chiapas'), ('Chihuahua', 'Chihuahua'), ('Ciudad de México', 'Ciudad de México'), ('Durango', 'Durango'), ('Guanajuato', 'Guanajuato'), ('Guerrero', 'Guerrero'), ('Hidalgo', 'Hidalgo'), ('Jalisco', 'Jalisco'), ('México', 'México'), ('Michoacán', 'Michoacán'), ('Morelos', 'Morelos'), ('Nayarit', 'Nayarit'), ('Nuevo León', 'Nuevo León'), ('Oaxaca', 'Oaxaca'), ('Puebla', 'Puebla'), ('Querétaro', 'Querétaro'), ('Quintana Roo', 'Quintana Roo'), ('San Luis Potosí', 'San Luis Potosí'), ('Sinaloa', 'Sinaloa'), ('Sonora', 'Sonora'), ('Tabasco', 'Tabasco'), ('Tamaulipas', 'Tamaulipas'), ('Tlaxcala', 'Tlaxcala'), ('Veracruz', 'Veracruz'), ('Yucatán', 'Yucatán'), ('Zacatecas', 'Zacatecas')], max_length=35, null=True, verbose_name='Estado')),
                ('estatus_cliente', models.IntegerField(choices=[(1, 'Activo'), (2, 'Suspendido'), (3, 'Baja')], default=1, verbose_name='Estatus')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
                'ordering': ['apellidos', 'nombre'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Indentificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_ip', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=90)),
                ('correo', models.EmailField(max_length=255)),
                ('celular', models.CharField(max_length=90)),
                ('numero_hilo', models.CharField(max_length=64)),
                ('observacion', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Identificación',
                'verbose_name_plural': 'Identificaciones',
                'db_table': 'Identificacion',
                'ordering': ['num_ip'],
                'unique_together': {('num_ip',)},
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='MensajePicky',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=255, null=True, verbose_name='Token')),
                ('number', models.CharField(max_length=50, verbose_name='Number')),
                ('message_in', models.CharField(max_length=255, verbose_name='Mensage in')),
                ('message_in_raw', models.CharField(max_length=255, verbose_name='Mensaje in raw')),
                ('message', models.CharField(blank=True, max_length=255, null=True, verbose_name='Mensaje')),
                ('application', models.CharField(blank=True, max_length=255, null=True, verbose_name='Aplicación')),
                ('tipo', models.CharField(default=2, max_length=255, verbose_name='Type')),
                ('unique_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='Unique id')),
                ('quoted', models.CharField(blank=True, max_length=255, null=True, verbose_name='Quoted')),
                ('estatus_mensaje', models.IntegerField(choices=[(0, 'Terminado'), (1, 'Activo')], default=1, verbose_name='Estatus del mensaje')),
                ('fecha_alta', models.DateTimeField(auto_now_add=True, verbose_name='Fecha alta')),
                ('opcion0', models.CharField(default='0', max_length=10, verbose_name='Acción')),
                ('opcion1', models.CharField(default='0', max_length=10, verbose_name='Opción Bien')),
                ('opcion2', models.CharField(default='0', max_length=10, verbose_name='Opción Estado')),
                ('opcion2_texto', models.CharField(blank=True, default=' ', max_length=40, null=True, verbose_name='Opción Estado texto')),
                ('opcion3', models.CharField(default='0', max_length=100, verbose_name='Opción Municipio')),
                ('opcion3_texto', models.CharField(blank=True, default=' ', max_length=200, null=True, verbose_name='Opción Municipio texto')),
            ],
            options={
                'verbose_name': 'Mensaje picky',
                'verbose_name_plural': 'Mensajes picky',
                'db_table': 'MensajePicky',
                'ordering': ['id'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seleccion', models.IntegerField(verbose_name='Selección')),
                ('opcion', models.CharField(max_length=2, verbose_name='Opción')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Opción Menú',
                'verbose_name_plural': 'Opciones Menú',
                'db_table': 'Menu',
                'ordering': ['seleccion', 'opcion'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Prueba',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=255, verbose_name='Descripción')),
                ('fecha', models.TimeField(auto_now_add=True, verbose_name='Fecha')),
            ],
            options={
                'verbose_name': 'Dato Prueba',
                'verbose_name_plural': 'Datos pruebas',
                'db_table': 'Prueba',
                'ordering': ['-fecha'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_created=True)),
                ('recibe', models.CharField(max_length=255)),
                ('envia', models.CharField(max_length=255)),
                ('identif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.indentificacion')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'db_table': 'Mensaje',
                'ordering': ['-fecha'],
            },
            bases=(models.Model, django.contrib.auth.mixins.PermissionRequiredMixin),
        ),
    ]
