# Generated by Django 4.0.4 on 2023-03-01 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Asesor',
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.RemoveField(
            model_name='mensaje',
            name='identif',
        ),
        migrations.DeleteModel(
            name='Indentificacion',
        ),
        migrations.DeleteModel(
            name='Mensaje',
        ),
    ]
