# Generated by Django 4.0.4 on 2023-03-04 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_delete_asesor_delete_cliente_remove_mensaje_identif_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mensajepicky',
            name='opcion0',
        ),
        migrations.RemoveField(
            model_name='mensajepicky',
            name='opcion2_texto',
        ),
        migrations.RemoveField(
            model_name='mensajepicky',
            name='opcion3_texto',
        ),
        migrations.AddField(
            model_name='mensajepicky',
            name='opcion4',
            field=models.JSONField(blank=True, null=True, verbose_name='Municipio'),
        ),
        migrations.AlterField(
            model_name='mensajepicky',
            name='opcion1',
            field=models.JSONField(blank=True, null=True, verbose_name='Acción'),
        ),
        migrations.AlterField(
            model_name='mensajepicky',
            name='opcion2',
            field=models.JSONField(blank=True, null=True, verbose_name='Bien'),
        ),
        migrations.AlterField(
            model_name='mensajepicky',
            name='opcion3',
            field=models.JSONField(blank=True, null=True, verbose_name='Estado'),
        ),
    ]
