# Generated by Django 4.0.4 on 2023-03-05 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_mensajepicky_options_bien_fecha_alta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajepicky',
            name='nivel',
            field=models.IntegerField(default=1, verbose_name='Nivel de pregunta'),
        ),
    ]
