# Generated by Django 4.0.4 on 2023-03-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_mensajepicky_nivel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bien',
            name='compra',
        ),
        migrations.RemoveField(
            model_name='bien',
            name='renta',
        ),
        migrations.AddField(
            model_name='bien',
            name='compra_renta',
            field=models.IntegerField(choices=[(0, 'Sin acción'), (1, 'Comprar'), (2, 'Rentar'), (3, 'Compra o Rentar')], default=0, verbose_name='Compra y/o renta'),
        ),
    ]
