# Generated by Django 4.0.4 on 2023-03-06 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_bien_compra_remove_bien_renta_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bien',
            name='estado',
            field=models.IntegerField(choices=[('0', 'Sin Estado'), ('1', 'Aguascalientes'), ('2', 'Baja California'), ('3', 'Baja California Sur'), ('4', 'Campeche'), ('5', 'Coahuila'), ('6', 'Colima'), ('7', 'Chiapas'), ('8', 'Chihuahua'), ('9', 'Ciudad de México'), ('10', 'Durango'), ('11', 'Guanajuato'), ('12', 'Guerrero'), ('13', 'Hidalgo'), ('14', 'Jalisco'), ('15', 'México'), ('16', 'Michoacán'), ('17', 'Morelos'), ('18', 'Nayarit'), ('19', 'Nuevo León'), ('20', 'Oaxaca'), ('21', 'Puebla'), ('22', 'Querétaro'), ('23', 'Quintana Roo'), ('24', 'San Luis Potosí'), ('25', 'Sinaloa'), ('26', 'Sonora'), ('27', 'Tabasco'), ('28', 'Tamaulipas'), ('29', 'Tlaxcala'), ('30', 'Veracruz'), ('31', 'Yucatán'), ('32', 'Zacatecas')], default=0, verbose_name='Estado'),
        ),
    ]
