# Generated by Django 4.0.4 on 2023-03-06 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_bien_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensajepicky',
            name='opcion5',
            field=models.JSONField(blank=True, null=True, verbose_name='Bien seleccionado'),
        ),
    ]
