# Generated by Django 4.0.4 on 2023-03-06 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_mensajepicky_opcion5'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Menu',
        ),
    ]
